#!/bin/bash

## Looks for staged .ts and .html files, and only runs them against the linter, as opposed to the whole codebase --> more efficient.


clear
fileList=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(ts|html)$')
if [ ${#fileList} -lt 1 ]; then
    echo -e "You have no staged .ts or .html files to test\n"
    exit
fi
npx eslint ${fileList[*]} "$@" ## --fix is a positional parameter acquired from within the calling command via "$@" here.
if [ $? -ne 0 ]; then
    echo -e "\nPlease fix the above linting issues before committing.\n"
    exit 1
fi